export const PING_BUTTON ='PING_BUTTON';
export const PING_BUTTON_OK ='PING_BUTTON_OK';
export const PING_MANINTHEMIDDLE ='PING_MANINTHEMIDDLE';
export const PING_MANINTHEMIDDLE_OK ='PING_MANINTHEMIDDLE_OK';
